(() => {
  'use strict';
  const D = window.RAS_DATA;
  const app = document.querySelector('#app');
  const fmt = new Intl.NumberFormat('it-IT');
  const money = new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0});
  const routes = ['home','governance','planning','staff','interventions','quality','cam','reports'];
  const state = {lot:'all',entity:'all',structure:'all',period:'30',role:'Responsabile Convenzione',view:'table',tab:'overview',slide:0,slider:null};

  const riskClasses=[{code:'AAR',label:'Altissimo Rischio',color:'#ed230a'},{code:'AR',label:'Alto Rischio',color:'#fead00'},{code:'MR',label:'Medio Rischio',color:'#ffd931'},{code:'BR',label:'Basso Rischio',color:'#d6f3cf'},{code:'AE',label:'Aree Esterne',color:'#ebebeb'}];
  const riskTotals=()=>riskClasses.map((_,i)=>activeEntities().filter(e=>state.entity==='all'||e.id===state.entity).reduce((sum,e)=>sum+e.risk[i],0));
  const riskBadge=i=>`<span class="risk-badge" style="background:${riskClasses[i].color}">${riskClasses[i].label} (${riskClasses[i].code})</span>`;
  function distributionGradient(values,colors){const total=values.reduce((a,b)=>a+b,0);let start=0;return 'conic-gradient('+values.map((v,i)=>{const end=start+v/total*100;const part=`${colors[i]} ${start}% ${end}%`;start=end;return part}).join(',')+')';}
  const catalogIcons = {products:'spray',materials:'paper-roll',machines:'vacuum',equipment:'mop',uniforms:'users'};
  const icon = (name) => `<svg class="ui-icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;
  const badge = (text,type='') => `<span class="badge ${type}"><i class="status-dot"></i>${text}</span>`;
  const safe = (value='') => String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const route = () => { const r=location.hash.replace(/^#\/?/,'').split('/')[0]||'home'; return routes.includes(r)?r:'home'; };
  const statusType = s => /Crit|Over|ritardo|Non|scad|Aperta/i.test(s)?'danger':/Warning|Riord|Manut|Verifica|sosp/i.test(s)?'warning':/Pian|In corso|presa|Autoriz/i.test(s)?'info':'';
  const activeEntities = () => state.lot==='all'?D.lots.flatMap(l=>l.entities):D.lots.find(l=>l.id===state.lot).entities;
  const activeSurface = () => state.entity!=='all' ? D.lots.flatMap(l=>l.entities).find(e=>e.id===state.entity)?.surface||0 : state.lot==='all'?D.meta.totalSurface:D.lots.find(l=>l.id===state.lot).surface;
  const scaled = (n,min=.35) => Math.round(n*(state.lot==='all'?1:Math.max(min,activeSurface()/D.meta.totalSurface)));
  const lotName = () => state.lot==='all'?'Tutti i lotti':`Lotto ${state.lot}`;
  const selectedEntity = () => state.entity==='all'?'Tutti gli enti':activeEntities().find(e=>e.id===state.entity)?.name||'Tutti gli enti';
  const kpis = () => [
    ['grid','Lotti attivi',state.lot==='all'?D.lots.length:1,'+0% vs mese prec.',''],
    ['building','Enti/Aziende',state.entity==='all'?activeEntities().length:1,'+0%',''],
    ['chart','Mq gestiti',fmt.format(activeSurface()),'+2,3%',''],
    ['shield','Attività completate',state.lot==='all'?'96,8%':`${(95.6+Number(state.lot)*.25).toFixed(1).replace('.',',')}%`,'+1,2%',''],
    ['clock','Ore erogate',fmt.format(scaled(18420)),'+4,8%',''],
    ['alert','NC aperte',scaled(14,.25),'+27%','critical'],
    ['leaf','CAM Compliance',state.lot==='all'?'97,2%':`${(96.2+Number(state.lot)*.18).toFixed(1).replace('.',',')}%`,'+0,6%',''],
    ['chart','Importo a consumo',money.format(scaled(412000)),'+8,1%','']
  ];

  function filtersTemplate(inHero=true){
    const entities=activeEntities();
    return `<section class="master-filter ${inHero?'':'inline-filter'}" aria-label="Filtri principali">
      <div class="field"><label for="lotFilter">Lotto</label><select id="lotFilter"><option value="all">Tutti i lotti</option>${D.lots.map(l=>`<option value="${l.id}" ${state.lot===l.id?'selected':''}>${l.name}</option>`).join('')}</select></div>
      <div class="field"><label for="entityFilter">Ente</label><select id="entityFilter"><option value="all">Tutti gli enti</option>${entities.map(e=>`<option value="${e.id}" ${state.entity===e.id?'selected':''}>${e.name}</option>`).join('')}</select></div>
      <div class="field"><label for="structureFilter">Presidio / Struttura</label><select id="structureFilter"><option value="all">Tutte le strutture</option><option value="network">Rete strutture — ${safe(selectedEntity())}</option></select></div>
      <div class="field"><label for="periodFilter">Periodo</label><select id="periodFilter"><option value="today">Oggi</option><option value="7">Ultimi 7 giorni</option><option value="30" ${state.period==='30'?'selected':''}>Ultimi 30 giorni</option><option value="90">Ultimi 3 mesi</option><option value="180">Ultimi 6 mesi</option><option value="year">Anno corrente</option><option value="custom">Custom range</option></select></div>
      <button class="btn" id="applyFilters">Aggiorna vista →</button><button class="ghost-btn" id="resetFilters" aria-label="Reset filtri">Reset</button>
      <div class="filter-summary">${lotName()} · ${selectedEntity()}</div>
    </section>`;
  }

  const kpiTemplate = () => `<section class="kpi-strip" aria-label="Indicatori principali">${kpis().map((k,i)=>`<button class="kpi card ${k[4]}" data-kpi="${i}" title="Apri dettaglio ${k[1]}"><span class="kpi-icon">${icon(k[0])}</span><label>${k[1]}</label><strong>${k[2]}</strong><small>▲ ${k[3]}</small></button>`).join('')}</section>`;
  const spark = seed => `<div class="spark" aria-hidden="true">${Array.from({length:9},(_,i)=>`<i style="height:${20+((i*17+seed*11)%30)}px"></i>`).join('')}</div>`;


  const chartMonths=['Apr','Mag','Giu','Lug','Ago','Set'];
  function metricChart(title,values,labels=chartMonths,unit='',max=null){
    const limit=max||Math.max(...values)*1.15;
    return `<figure class="metric-chart"><figcaption>${title} <small>· ${unit} · demo</small></figcaption><div class="metric-bars">${values.map((v,i)=>`<div class="metric-column"><b>${String(v).replace('.',',')}</b><i style="height:${Math.max(2,v/limit*62)}px" title="${labels[i]}: ${v} ${unit}"></i><span>${labels[i]}</span></div>`).join('')}</div></figure>`;
  }
  function functionalChart(i){
    const configs=[['Enti per lotto',D.lots.map(l=>l.entities.length),D.lots.map(l=>'L'+l.id),'enti'],['Attività completate',[94.1,94.8,95.2,95.9,96.2,96.8],chartMonths,'%'],['Ore erogate',[17100,17420,17900,18010,18150,18420],chartMonths,'ore'],['Ticket aperti',[64,71,68,78,80,84],chartMonths,'ticket'],['Controlli effettuati',[96,102,110,118,121,128],chartMonths,'controlli'],['Cataloghi reali',[15,11,19,32],['Prod.','Mat.','Macc.','Attr.'],'record'],['Report generati',[29,32,38,41,45,48],chartMonths,'report']];
    const c=configs[i]; return metricChart(...c);
  }
  function satisfactionChart(){
    const values=[4.1,4.3,4.4,4.3,4.5,4.6];
    const x=i=>42+i*58, y=v=>132-v/5*110;
    return `<figure class="satisfaction-chart"><figcaption>Valutazione media · scala 0–5 <small>Apr–Set 2026 · demo</small></figcaption><svg viewBox="0 0 360 168" role="img" aria-label="Soddisfazione mensile: aprile 4,1; maggio 4,3; giugno 4,4; luglio 4,3; agosto 4,5; settembre 4,6 su 5">${[0,1,2,3,4,5].map(v=>`<line x1="35" x2="340" y1="${y(v)}" y2="${y(v)}" stroke="#dce8ef"/><text x="20" y="${y(v)+4}">${v}</text>`).join('')}<polyline points="${values.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}" fill="none" stroke="#1189ba" stroke-width="2"/>${values.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="3" fill="#1189ba"/><text x="${x(i)}" y="${y(v)-9}" text-anchor="middle">${String(v).replace('.',',')}</text><text x="${x(i)}" y="155" text-anchor="middle">${chartMonths[i]}</text>`).join('')}</svg></figure>`;
  }
  function qualityGauge(){return `<div class="quality-summary"><div><svg viewBox="0 0 200 120" class="lqa-gauge" role="img" aria-label="Indice LQA ponderato 98,1 pour cent"><path d="M20 95 A80 80 0 0 1 180 95" pathLength="100" stroke="#e4edf1"/><path d="M20 95 A80 80 0 0 1 180 95" pathLength="100" stroke="#179b96" stroke-dasharray="98.1 100"/><text x="100" y="83" text-anchor="middle">98,1%</text><text x="18" y="118" class="gauge-tick">0%</text><text x="157" y="118" class="gauge-tick">100%</text></svg><small>Indice LQA ponderato · demo</small></div><dl><div><dt>Controlli effettuati</dt><dd>128</dd></div><div><dt>Conformi</dt><dd>126</dd></div><div><dt>Non conformi</dt><dd>2</dd></div></dl></div>`;}
  function paretoChart(){return `<div class="pareto-readable"><p>NC aperte per causa · ultimi 30 giorni <small>Demo</small></p>${[['Pulizia non conforme',6],['Mancata frequenza',3],['Prodotti non idonei',2],['Attrezzature',2],['Altro',1]].map(([label,n])=>`<div><span>${label}</span><i style="--amount:${n/6*100}%"></i><b>${n}</b></div>`).join('')}<footer>Totale: <b>14 NC</b> · unità: numero di casi</footer></div>`;}

  function home(){
    const cards=[
      ['01','building','Governance & Anagrafiche','Enti, strutture, lotti e configurazioni del servizio.',[D.lots.flatMap(l=>l.entities).length,D.lots.length,'1.432'],['enti','lotti','ambienti'],'governance'],
      ['02','calendar','Pianificazione & POG','Piani operativi, cicli di pulizia e interventi periodici.',['1.248','38','96,8%'],['attività','risanamenti','completate'],'planning'],
      ['03','users','Personale & Presenze','Turni, presenze, competenze e formazione.',['624','92,4%','18.420'],['operatori','copertura','ore'],'staff'],
      ['04','ticket','Interventi & Ticketing','Richieste, guasti, interventi extra e pronto intervento.',['84','12','€ 412K'],['ticket','SLA warning','valore'],'interventions'],
      ['05','shield','Qualità & Controlli','LQA, verifiche ispettive e non conformità.',['128','98,1%','14'],['controlli','conformità','NC aperte'],'quality'],
      ['06','leaf','CAM, Prodotti & Asset','Prodotti conformi, macchine, materiali e sostenibilità.',[D.products.length,D.materials.length,D.machines.length+D.equipment.length],['prodotti','materiali','asset'],'cam'],
      ['07','chart','Report & Analytics','Reportistica, esportazioni e viste direzionali.',['48','CSV/XLSX/PDF','7'],['report','formati','viste'],'reports']
    ];
    const heroImgs=['hero-01.webp','hero-02.webp','hero-03.webp'];
    return `<section class="hero" id="hero">
      <div class="slides">${heroImgs.map((img,i)=>`<div class="slide ${i===0?'active':''}" data-slide="${i}"><img src="./assets/${img}" alt="${['Operatrice durante il lavaggio di un corridoio ospedaliero','Pulizia di una superficie sanitaria con panno e spray','Operatore durante un intervento di derattizzazione'][i]}" ${i?'loading="lazy"':''}></div>`).join('')}</div>
      <div class="hero-inner"><div class="hero-copy"><span class="demo-label">Ambiente demo</span><span class="eyebrow">Sistema integrato di monitoraggio e rendicontazione</span><h1>RAS SERVICE HUB</h1><h2>Service Control & Environmental Performance</h2><p>Una control room unificata per pianificazione, esecuzione, controllo qualità, CAM e reporting.</p></div></div>
      <div class="slider-meta">${heroImgs.map((_,i)=>`<button class="dot ${i===0?'active':''}" data-slide-to="${i}" aria-label="Vai alla slide ${i+1}"></button>`).join('')}</div><div class="slide-progress play"><i></i></div>
    </section>
    ${filtersTemplate(true)}${kpiTemplate()}
    <div class="page-shell">
      <div class="section-heading"><div><h2>Il servizio, sotto controllo.</h2><p>Dati aggiornati, visione unificata, valore per la sanità della Sardegna.</p></div><div class="section-actions"><small>Ultimo aggiornamento: ${D.meta.updated}</small>${badge('Dati in tempo reale')}</div></div>
      <section class="overview-grid home-overview">
        <article class="card chart-card"><div class="card-title"><div><h3>Attività programmate vs eseguite</h3><p>Andamento mensile delle attività di pulizia e sanificazione</p></div><select class="mini-select" id="chartPeriod"><option>6 mesi</option><option>3 mesi</option><option>12 mesi</option></select></div><div class="bar-chart">${['Apr','Mag','Giu','Lug','Ago','Set'].map((m,i)=>`<button class="bar-group" data-month="${m}" title="Apri dettaglio ${m}" style="border:0;background:none"><i style="height:${62+i*4}%"></i><i style="height:${58+i*3}%"></i><span>${m}</span></button>`).join('')}</div></article>
        <article class="card chart-card"><div class="card-title"><div><h3>Ore previste vs effettive</h3><p>Copertura del programma operativo</p></div></div><div class="donut-wrap"><button class="radial" style="--pct:98.7;border:0" data-detail="hours"><strong>98,7%</strong></button><div class="radial-sub"><span><b>${fmt.format(scaled(18650))}</b><small>Ore previste</small></span><span><b>${fmt.format(scaled(18420))}</b><small>Ore effettive</small></span></div></div></article>
        <article class="card chart-card"><div class="card-title"><div><h3>Distribuzione per Lotto</h3><p>Superficie contrattuale</p></div></div><div class="donut-wrap"><button class="donut" data-detail="lots" style="border:0;background:${distributionGradient(D.lots.map(l=>l.surface),['#2182b5','#5cbdd1'])}"><span>${fmt.format(D.meta.totalSurface)}<br><small>m²</small></span></button><div class="legend">${D.lots.map((l,i)=>`<button class="link-btn" data-lot-jump="${l.id}"><span><i style="background:${['#2182b5','#5cbdd1','#92c9ea','#1aa1a0'][i]}"></i>${l.name} <b>${(l.surface/D.meta.totalSurface*100).toFixed(1).replace('.',',')}%</b></span></button>`).join('')}</div></div></article>
        <article class="card risk-codes"><div class="risk-heading"><h3>Codici colore complessità aree sanitarie</h3><button class="link-btn" data-classification>Scopri la classificazione →</button></div>${riskClasses.map((r,i)=>`<button class="risk-item" data-risk="${i}" style="--risk-color:${r.color}"><strong>${r.code}</strong><span>${r.label}</span><small>${fmt.format(riskTotals()[i])} m²</small></button>`).join('')}</article>
      </section>
      <div class="section-heading"><div><h2>Aree funzionali</h2><p>Tutti i processi, un’unica piattaforma.</p></div><button class="link-btn" data-action="personalize">▦ Personalizza la tua vista</button></div>
      <section class="functional-grid">${cards.map((c,i)=>`<article class="card functional-card ${i===5?'cam-card':''}" data-nav="${c[6]}" tabindex="0"><span class="card-index">${c[0]}</span><span class="card-icon">${icon(c[1])}</span><h3>${c[2]}</h3><p>${c[3]}</p><div class="card-kpis">${c[4].map((v,j)=>`<span><b>${v}</b><small>${c[5][j]}</small></span>`).join('')}</div>${functionalChart(i)}<button class="link-btn" data-nav="${c[6]}">Apri sezione →</button></article>`).join('')}
        <article class="card sardinia-card"><img src="./assets/sardegna-card.webp" alt="Un servizio di qualità per una Sardegna più sana." loading="lazy"></article>
      </section>
      <div class="section-heading"><div><h2>Qualità in tempo reale</h2><p>Controlli, non conformità e soddisfazione, sempre aggiornati.</p></div><button class="link-btn" data-nav="quality">Vai alla sezione Qualità →</button></div>
      <section class="quality-grid"><article class="card quality-card"><div class="card-title"><h3>LQA / Conformità</h3></div>${qualityGauge()}</article><article class="card quality-card"><div class="card-title"><h3>Non Conformità · Pareto</h3></div>${paretoChart()}</article><article class="card quality-card"><div class="card-title"><h3>Customer Satisfaction</h3>${badge('+12,2% da aprile')}</div><strong style="font-size:32px">4,6 <small>/ 5</small></strong>${satisfactionChart()}</article></section>
      <div class="section-heading"></div>
      <section class="card cam-preview"><div class="cam-head"><div><span class="eyebrow">Environmental performance</span><h2>CAM Control Center</h2><p>Performance ambientale, risultati concreti.</p></div><button class="btn" data-nav="cam">Apri CAM Control Center →</button></div><div class="cam-kpis">${[['Prodotti conformi CAM','15 / 15'],['Prodotti Ecolabel','10'],['Consumo detergente / mq','3,2 g'],['Ore macchina','2.840'],['Materiale economale','11 record']].map((x,i)=>`<div><small>${x[0]}</small><strong>${x[1]}</strong><em style="color:${i===3?'var(--amber)':'var(--green)'}">${i===3?'▲ 6%':'▲ 4,1%'}</em></div>`).join('')}</div><div class="table-wrap" style="max-height:280px"><table class="data-table"><thead><tr><th>Prodotto</th><th>Categoria</th><th>CAM</th><th>Certificazioni</th><th>Consumo g/mq</th></tr></thead><tbody>${D.products.slice(0,5).map(p=>`<tr data-product="${p.id}"><td data-label="Prodotto"><b>${p.name}</b></td><td data-label="Categoria">${p.category}</td><td data-label="CAM">${badge('Conforme')}</td><td data-label="Certificazioni">${p.certifications}</td><td data-label="Consumo">${String(p.consumption).replace('.',',')}</td></tr>`).join('')}</tbody></table></div></section>
      <div class="section-heading"><div><h2>Ultimi eventi</h2><p>Le attività più recenti nel sistema.</p></div><button class="link-btn" data-detail="events">Vedi tutti gli eventi →</button></div>
      <section class="activity-grid"><article class="card feed">${[['12:08','Nuovo ticket aperto — Guasto dispenser sapone','ASL 8 Cagliari','Aperto'],['10:15','Non conformità chiusa','ASL 7 Sulcis','Risolta'],['09:30','Intervento periodico programmato','AO Brotzu','Pianificato']].map(e=>`<div class="feed-item"><time>${e[0]}</time><b>${e[1]}</b><span>${e[2]}</span>${badge(e[3],statusType(e[3]))}</div>`).join('')}</article><article class="card notification-list">${notificationItems(false)}</article></section>
    </div>`;
  }

  function pageHero(title,subtitle,iconName,actions=''){
    return `<section class="page-hero${route()==='cam'?' cam-page-hero':''}"><div class="inner"><div><div class="crumb">Home / ${title}</div><span class="eyebrow">${icon(iconName)} Control room operativa</span><h1>${title}</h1><p>${subtitle}</p></div><div class="section-actions">${actions}</div></div></section>`;
  }
  function tabs(items,active='overview'){return `<nav class="subnav" aria-label="Sezioni">${items.map(i=>`<button data-tab="${i[0]}" class="${(state.tab||active)===i[0]?'active':''}">${i[1]}</button>`).join('')}</nav>`}
  function toolbar(placeholder,actions=''){return `<div class="toolbar"><label class="search-field">${icon('search')}<input type="search" data-local-search placeholder="${placeholder}" aria-label="${placeholder}"></label><div class="toolbar-group"><button class="ghost-btn" data-action="filter">${icon('filter')} Filtri</button><button class="ghost-btn" data-action="export">${icon('download')} Esporta</button>${actions}</div></div>`}
  function stats(items){return `<section class="stat-grid">${items.map(s=>`<article class="card stat-card"><small>${s[0]}</small><strong>${s[1]}</strong><em>${s[2]||'Dati demo aggiornati'}</em></article>`).join('')}</section>`}
  function notificationItems(all=true){const arr=[['!','Nuove non conformità','3 nuove NC nella tua area di competenza','2 min'],['⌁','Scadenza documento','SDS in scadenza — Detergente Ecolabel','1 ora'],['▣','Report mensile disponibile','Report di settembre pronto per il download','3 ore'],['⚙','Manutenzione in scadenza','FIMAP EMx — manutenzione tra 4 giorni','5 ore'],['✓','Controllo programmato','Controllo LQA — AO Brotzu','domani']];return arr.slice(0,all?5:3).map(n=>`<button class="notification" data-action="notification" style="border:0;background:transparent;width:100%;text-align:left"><i>${n[0]}</i><span><b>${n[1]}</b><small>${n[2]}</small></span><small>${n[3]}</small></button>`).join('')}

  function governance(){
    const t=state.tab;
    let content='';
    if(t==='entities'||t==='overview') content=`${stats([['Lotti attivi',D.lots.length,'Perimetro 4–5'],['Enti/Aziende',D.lots.flatMap(l=>l.entities).length,'Dipendenza Lotto→Ente attiva'],['Superficie complessiva',fmt.format(D.meta.totalSurface)+' m²','Dato Allegato 1E'],['Variazioni aperte','6','Demo operativa']])}<div class="content-grid"><article class="card panel"><h3>Gerarchia contrattuale</h3><div class="hierarchy">${D.lots.map(l=>`<div class="tree-row" data-lot-jump="${l.id}"><span>${icon('grid')}</span><b>${l.name} · ${fmt.format(l.surface)} m²</b>${badge(`${l.entities.length} enti`,'info')}</div>${l.entities.map(e=>`<div class="tree-row"><span></span><span class="level" style="--level:1"><b>${e.name}</b><small style="display:block;color:#718595">${fmt.format(e.surface)} m²</small></span><button class="link-btn" data-entity-detail="${e.id}">Dettaglio →</button></div>`).join('')}`).join('')}</div></article><aside class="card panel"><h3>Distribuzione per rischio</h3><div class="donut" style="margin:18px auto;background:${distributionGradient(riskTotals(),riskClasses.map(r=>r.color))}"><span>${fmt.format(activeSurface())}<br><small>m²</small></span></div><div class="legend">${riskClasses.map((r,i)=>`<span><i style="background:${r.color}"></i>${r.label} (${r.code}) · ${fmt.format(riskTotals()[i])} m²</span>`).join('')}</div></aside></div>`;
    if(t==='structures'||t==='areas') content=`${toolbar('Cerca edificio, piano, area o ambiente')}<div class="table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>Ente</th><th>Gerarchia</th><th>Destinazione</th><th>Mq</th><th>Codice</th><th>Stato</th><th>Aggiornamento</th></tr></thead><tbody>${activeEntities().flatMap((e,ei)=>Array.from({length:4},(_,i)=>`<tr data-room="${e.id}-${i}"><td data-label="ID">AMB-${String(ei+1).padStart(2,'0')}${i+1}</td><td data-label="Ente"><b>${e.name}</b></td><td data-label="Gerarchia">Edificio ${i+1} · Piano ${i%3} · Area ${String.fromCharCode(65+i)}</td><td data-label="Destinazione">${['Degenza','Ambulatorio','Servizi generali','Area esterna'][i]}</td><td data-label="Mq">${fmt.format(Math.round(e.surface/(16+i)))}</td><td data-label="Codice">${riskBadge([0,1,3,4][i])}</td><td data-label="Stato">${badge(i===2?'Variazione':'Attivo',i===2?'warning':'')}</td><td data-label="Aggiornamento">20 set 2026</td></tr>`)).join('')}</tbody></table></div>`;
    if(t==='roles') content=`${stats([['Utenti attivi','48'],['Profili RBAC','9'],['Accessi oggi','127'],['Sessioni sospette','0','Nessuna anomalia']])}<div class="content-grid"><article class="card panel"><h3>Profili e autorizzazioni</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Profilo</th><th>Ambito</th><th>Utenti</th><th>Permessi</th></tr></thead><tbody>${[['Super Admin','Tutti i lotti',2],['Responsabile Convenzione','Tutti i lotti',3],['Responsabile Lotto','Lotto assegnato',8],['DEC','Ente / Presidio',7],['RUP','Ente',4],['Referente Ente','Ente',7],['Referente Presidio','Presidio',9],['Qualità / Auditor','Controlli',5],['Operatore','Attività assegnate',624]].map(r=>`<tr><td data-label="Profilo"><b>${r[0]}</b></td><td data-label="Ambito">${r[1]}</td><td data-label="Utenti">${r[2]}</td><td data-label="Permessi"><button class="link-btn" data-permissions="${r[0]}">Gestisci →</button></td></tr>`).join('')}</tbody></table></div></article><aside class="card panel"><h3>Permission matrix</h3><p style="color:var(--muted)">Accessi contestuali per funzione, Lotto, Ente e Presidio.</p>${['Visualizza dashboard','Gestisci anagrafiche','Valida POG','Gestisci NC','Esporta report','Amministra utenti'].map((x,i)=>`<label style="display:flex;justify-content:space-between;padding:11px 0;border-bottom:1px solid var(--line)">${x}<input type="checkbox" ${i<4?'checked':''}></label>`).join('')}<button class="btn" data-action="save-permissions" style="margin-top:16px;width:100%">Salva autorizzazioni</button></aside></div>`;
    if(t==='documents'||t==='audit') content=`${toolbar(t==='documents'?'Cerca documento':'Cerca evento audit')}<div class="document-grid">${Array.from({length:9},(_,i)=>`<button class="card doc-card" data-action="document"><span>${icon('doc')}</span><span><b>${t==='documents'?['PDI','OPF','OFA','Anagrafica locali','Planimetria','Verbale avvio','Registro variazioni','Atto autorizzativo','Report semestrale'][i]:`AUD-${20260+i}`}</b><small>${t==='documents'?'Documento contrattuale · PDF':`Modifica ${['anagrafica','ruolo','struttura'][i%3]} · Admin Demo`}</small></span><span>→</span></button>`).join('')}</div>`;
    return `${pageHero('Governance & Anagrafiche','Enti, strutture, gerarchia immobiliare, profilazione e tracciabilità completa.','building','<button class="btn" data-action="new-record">+ Nuova anagrafica</button>')}<div class="page-shell">${tabs([['overview','Overview'],['entities','Enti'],['structures','Strutture'],['areas','Aree / Ambienti'],['roles','Utenti & Ruoli'],['documents','Documenti'],['audit','Audit trail']])}${content}</div>`;
  }

  function planning(){
    const t=state.tab; let content='';
    if(t==='today'||t==='overview') content=`${stats([['Attività previste','1.248'],['In corso','86'],['Completate','96,8%'],['Ritardi / non eseguite','12', 'SLA sotto osservazione']])}${toolbar('Cerca attività, area o operatore','<button class="btn" data-action="new-activity">+ Pianifica attività</button>')}<div class="table-wrap"><table class="data-table"><thead><tr><th>Ora</th><th>Ente</th><th>Area</th><th>Attività</th><th>Operatore</th><th>Durata</th><th>Stato</th></tr></thead><tbody>${D.activities.map((a,i)=>`<tr data-activity="${a.id}"><td data-label="Ora">${a.time}</td><td data-label="Ente"><b>${a.entity}</b></td><td data-label="Area">${a.area}</td><td data-label="Attività">${a.task}</td><td data-label="Operatore">${a.operator}</td><td data-label="Durata">${45+i*15} min</td><td data-label="Stato">${badge(a.status,statusType(a.status))}</td></tr>`).join('')}</tbody></table></div>`;
    if(t==='calendar') content=`${toolbar('Cerca nel calendario','<button class="ghost-btn" data-action="calendar-view">Giorno · Settimana · Mese</button>')}<article class="card panel"><div class="card-title"><h3>Settembre 2026</h3><div><button class="ghost-btn">‹</button><button class="ghost-btn">Oggi</button><button class="ghost-btn">›</button></div></div><div class="calendar-grid">${Array.from({length:35},(_,i)=>`<button class="day" data-day="${i+1}" style="text-align:left"><b>${i<5?'':i-4}</b>${i>5&&i%3===0?`<span>${['POG · Pulizia ordinaria','Risanamento','Controllo LQA'][i%3]}</span>`:''}</button>`).join('')}</div></article>`;
    if(t==='pog'||t==='periodic') content=`${stats([['POG da validare','8'],['Squadre assegnate','42'],['Copertura','92,4%'],['Durata effettiva','18.420 h']])}${toolbar('Cerca POG o attività periodica','<button class="btn" data-action="validate-pog">Valida selezionati</button>')}<div class="table-wrap"><table class="data-table"><thead><tr><th>Data</th><th>Ente</th><th>Area</th><th>Attività</th><th>Operatore / Squadra</th><th>Fascia</th><th>Prevista</th><th>Effettiva</th><th>Stato</th></tr></thead><tbody>${D.activities.concat(D.activities).map((a,i)=>`<tr data-activity="${a.id}"><td data-label="Data">${22+(i%5)} set 2026</td><td data-label="Ente">${a.entity}</td><td data-label="Area">${a.area}</td><td data-label="Attività"><b>${a.task}</b></td><td data-label="Operatore">${a.operator}</td><td data-label="Fascia">${a.time}–${String(Number(a.time.slice(0,2))+2).padStart(2,'0')}:00</td><td data-label="Prevista">120 min</td><td data-label="Effettiva">${108+i*3} min</td><td data-label="Stato">${badge(a.status,statusType(a.status))}</td></tr>`).join('')}</tbody></table></div>`;
    if(t==='reclamation') content=`${stats([['Risanamenti pianificati','38'],['In esecuzione','7'],['Completati','29'],['Scostamento medio','−2,4%']])}<article class="card panel"><div class="card-title"><h3>Timeline risanamenti · Settembre</h3><button class="btn" data-action="new-reclamation">+ Nuovo risanamento</button></div><div class="gantt">${['ASL 7 · Area alto rischio','ASL 8 · Degenza','AO Brotzu · Blocco operatorio'].map((x,i)=>`<div class="gantt-label">${x}<small style="display:block;color:#728692">${740+i*220} m²</small></div><button class="gantt-bar" data-action="gantt" style="--start:${2+i};--span:${4+(i%3)};border:0" title="${x}"></button>`).join('')}</div></article>`;
    return `${pageHero('Pianificazione & POG','Piani operativi giornalieri, cicli, frequenze e risanamenti con avanzamento in tempo reale.','calendar','<button class="btn" data-action="new-activity">+ Nuova attività</button>')}<div class="page-shell">${tabs([['today','Oggi'],['calendar','Calendario'],['pog','POG'],['reclamation','Risanamenti'],['periodic','Attività periodiche']])}${content}</div>`;
  }

  function staff(){
    const t=state.tab; let content='';
    if(t==='registry'||t==='overview') content=`${stats([['Operatori','624'],['Copertura turni','92,4%'],['Ore erogate','18.420'],['Formazione in scadenza','18','Entro 30 giorni']])}${toolbar('Cerca nome, matricola o mansione','<button class="btn" data-action="new-person">+ Nuovo operatore</button>')}<div class="table-wrap"><table class="data-table"><thead><tr><th>Operatore</th><th>Matricola</th><th>Mansione</th><th>Lotto</th><th>Ente</th><th>Monte ore</th><th>Stato</th></tr></thead><tbody>${D.people.map(p=>`<tr data-person="${p.id}"><td data-label="Operatore"><b>${p.name}</b></td><td data-label="Matricola">${p.id}</td><td data-label="Mansione">${p.role}</td><td data-label="Lotto">Lotto ${p.lot}</td><td data-label="Ente">${p.entity}</td><td data-label="Monte ore">${p.hours} h</td><td data-label="Stato">${badge(p.status,statusType(p.status))}</td></tr>`).join('')}</tbody></table></div>`;
    if(t==='shifts'||t==='attendance') content=`${toolbar('Cerca turno o presenza','<button class="btn" data-action="new-shift">+ Assegna turno</button>')}<div class="content-grid"><article class="card panel"><h3>Copertura turni · oggi</h3><div class="calendar-grid">${['Lun','Mar','Mer','Gio','Ven','Sab','Dom'].map((d,i)=>`<div class="day"><b>${d} ${21+i}</b><span>07:00 · ${12-i%3} operatori</span><span>13:00 · ${9+i%4} operatori</span></div>`).join('')}</div></article><aside class="card panel"><h3>Presenze live</h3>${D.people.slice(0,6).map((p,i)=>`<div class="tree-row"><span>${badge(i===4?'Pausa':'Presente',i===4?'warning':'')}</span><span><b>${p.name}</b><small style="display:block">Ingresso ${p.shift.slice(0,5)}</small></span><small>${p.entity}</small></div>`).join('')}</aside></div>`;
    if(t==='activities') content=`${toolbar('Cerca attività per operatore')}<div class="table-wrap"><table class="data-table"><thead><tr><th>Operatore</th><th>Attività oggi</th><th>Completate</th><th>Tempo medio</th><th>Conformità</th><th>Evidenze</th></tr></thead><tbody>${D.people.map((p,i)=>`<tr data-person="${p.id}"><td data-label="Operatore"><b>${p.name}</b></td><td data-label="Attività">${8+i%5}</td><td data-label="Completate">${7+i%4}</td><td data-label="Tempo medio">${32+i} min</td><td data-label="Conformità">${98-(i%3)*.4}%</td><td data-label="Evidenze"><button class="link-btn">Apri →</button></td></tr>`).join('')}</tbody></table></div>`;
    if(t==='training') content=`${stats([['Corsi attivi','12'],['Attestati validi','606'],['In scadenza','18'],['Completamento','97,1%']])}<div class="report-grid">${['Detersione e disinfezione','Dosaggio e SDS','Gestione rifiuti sanitari','Protocolli aree infettive','Uso macchine e batterie','Microfibra e impregnazione'].map((x,i)=>`<article class="card report-card"><span class="catalog-icon">${icon('shield')}</span><h3>${x}</h3><p>Formazione conforme ai contenuti CAM e D.Lgs. 81/08.</p><div class="tags"><span class="tag">${82+i*3} partecipanti</span><span class="tag">Scadenza ${i+2}/2027</span></div><button class="link-btn" data-action="training">Apri registro →</button></article>`).join('')}</div>`;
    if(t==='uniforms') content=catalogSection('uniforms');
    return `${pageHero('Personale & Presenze','Anagrafica, turni, tracciabilità in tempo reale, formazione e dotazioni individuali.','users','<button class="btn" data-action="new-person">+ Nuovo operatore</button>')}<div class="page-shell">${tabs([['registry','Anagrafica'],['shifts','Turni'],['attendance','Presenze'],['activities','Attività'],['training','Formazione'],['uniforms','Divise & Dotazioni']])}${content}</div>`;
  }

  function interventions(){
    const t=state.tab; let content='';
    if(t==='list'||t==='overview') content=`${stats([['Ticket aperti','84'],['SLA warning','12'],['Overdue','4','Intervento richiesto'],['Importo a consumo','€ 412K']])}${toolbar('Cerca ticket, richiedente o area','<button class="btn" data-action="new-ticket">+ Nuova richiesta</button>')}<div class="table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>Richiesta</th><th>Tipo</th><th>Ente</th><th>Priorità</th><th>SLA residuo</th><th>Stato</th></tr></thead><tbody>${D.tickets.concat(D.tickets).map((x,i)=>`<tr data-ticket="${x.id}"><td data-label="ID"><b>${x.id}</b></td><td data-label="Richiesta">${x.title}</td><td data-label="Tipo">${x.type}</td><td data-label="Ente">${x.entity}</td><td data-label="Priorità">${badge(x.priority,statusType(x.priority))}</td><td data-label="SLA"><b style="color:${x.sla.startsWith('00')?'var(--red)':'inherit'}">${x.sla}</b></td><td data-label="Stato">${badge(x.status,statusType(x.status))}</td></tr>`).join('')}</tbody></table></div>`;
    if(t==='kanban') content=`${toolbar('Cerca nella board','<button class="btn" data-action="new-ticket">+ Nuova richiesta</button>')}<div class="kanban">${['Richiesta','Autorizzazione','Esecuzione','Verifica / Chiusura'].map((col,ci)=>`<section class="kanban-col"><h3>${col} · ${ci+2}</h3>${D.tickets.filter((_,i)=>i%4===ci).concat(ci===0?D.tickets.slice(0,2):[]).map(x=>`<button class="ticket-card" data-ticket="${x.id}" style="width:100%;text-align:left"><small>${x.id} · ${x.type}</small><b>${x.title}</b><small>${x.entity}</small><span style="display:flex;justify-content:space-between;margin-top:8px">${badge(x.priority,statusType(x.priority))}<b>${x.sla}</b></span></button>`).join('')}</section>`).join('')}</div>`;
    if(t==='timeline') content=`<article class="card panel"><div class="card-title"><div><h3>Timeline richiesta TCK-260913</h3><p>Risanamento area ad alto rischio · AO Brotzu</p></div>${badge('SLA 00:38','danger')}</div><div class="hierarchy">${[['09:12','Richiesta','Referente Presidio','Apertura tramite sistema'],['09:14','Presa in carico','Responsabile Lotto','Priorità critica'],['09:21','Autorizzazione','DEC','Importo autorizzato'],['09:32','Pianificazione','Caposquadra Demo','Squadra assegnata'],['10:05','Esecuzione','Squadra Demo A','Intervento in corso'],['—','Verifica','DEC','In attesa'],['—','Chiusura','Sistema','In attesa']].map((x,i)=>`<div class="tree-row"><span>${badge(i<5?'Completato':'In attesa',i===4?'info':i>4?'warning':'')}</span><span><b>${x[1]}</b><small style="display:block">${x[2]} · ${x[3]}</small></span><time>${x[0]}</time></div>`).join('')}</div></article>`;
    return `${pageHero('Interventi & Ticketing','Service Desk per extra-canone, attività a chiamata, straordinarie, anomalie e reclami.','ticket','<button class="btn" data-action="new-ticket">+ Nuova richiesta</button>')}<div class="page-shell">${tabs([['list','Elenco'],['kanban','Kanban'],['timeline','Timeline']])}${content}</div>`;
  }

  function quality(){
    const t=state.tab; let content='';
    if(t==='overview') content=`${stats([['Controlli','128'],['Conformità LQA','98,1%'],['NC aperte','14'],['Customer Satisfaction','4,6 / 5']])}<div class="quality-grid"><article class="card quality-card"><h3>Conformità LQA</h3>${qualityGauge()}</article><article class="card quality-card"><h3>Pareto non conformità</h3>${paretoChart()}</article><article class="card quality-card"><h3>Customer Satisfaction</h3><strong style="font-size:36px">4,6 <small>/ 5</small></strong><p>186 survey · +12,2% da aprile</p>${satisfactionChart()}</article></div>`;
    if(t==='process') content=`${toolbar('Cerca controllo di processo','<button class="btn" data-action="new-check">+ Nuova checklist</button>')}<div class="content-grid"><article class="card panel"><h3>Checklist dinamica</h3>${['Modalità di esecuzione','Protocolli di sicurezza','Rilevazione difformità','Azioni correttive','Aggiornamento anagrafiche','Rilevazione presenze','Reperibilità','Formazione del personale'].map((x,i)=>`<label style="display:grid;grid-template-columns:26px 1fr auto;gap:10px;padding:12px 0;border-bottom:1px solid var(--line)"><input type="checkbox" ${i!==3?'checked':''}><span><b>${x}</b><small style="display:block;color:#718595">Evidenza ${i+1} · ${i===3?'da verificare':'conforme'}</small></span>${badge(i===3?'Verifica':'Conforme',i===3?'warning':'')}</label>`).join('')}<button class="btn" data-action="complete-check" style="margin-top:16px">Completa controllo</button></article><aside class="card panel"><h3>Controlli programmati</h3>${D.lots.map((l,i)=>`<div class="tree-row"><span>${icon('calendar')}</span><span><b>${l.name}</b><small style="display:block">${l.entities[0].name}</small></span><time>${24+i} set</time></div>`).join('')}</aside></div>`;
    if(t==='result'||t==='lqa') content=`${stats([['LQA atteso','97,0%'],['LQA raggiunto','98,1%'],['Campioni','128'],['Elementi respinti','2']])}${toolbar('Cerca griglia di controllo','<button class="btn" data-action="new-lqa">+ Nuovo controllo LQA</button>')}<div class="table-wrap"><table class="data-table"><thead><tr><th>Griglia</th><th>Lotto di controllo</th><th>Categoria locale</th><th>Campione</th><th>LQA atteso</th><th>LQA raggiunto</th><th>Esito</th></tr></thead><tbody>${activeEntities().map((e,i)=>`<tr data-action="lqa-detail"><td data-label="Griglia"><b>LQA-${2609+i}</b></td><td data-label="Lotto">${e.name}</td><td data-label="Categoria">${['Area operatoria','Degenza','Ambulatorio','Area esterna'][i%4]}</td><td data-label="Campione">${18+i*4} zone</td><td data-label="Atteso">97,0%</td><td data-label="Raggiunto">${i===2?'96,8':'98,'+(i+1)}%</td><td data-label="Esito">${badge(i===2?'Rifiutato':'Accettato',i===2?'danger':'')}</td></tr>`).join('')}</tbody></table></div><p style="color:var(--muted);font-size:12px">Metodo: punteggio 0 = accettato, 1 = rifiutato; zona conforme se (1 − B/A) ≥ LQA.</p>`;
    if(t==='nc') content=`${stats([['NC aperte','14'],['Oltre SLA','4'],['Tempo medio chiusura','6 h 24 m'],['Risolte nel mese','36']])}${toolbar('Cerca non conformità','<button class="btn" data-action="new-nc">+ Apri NC</button>')}<div class="table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>Origine / Causa</th><th>Ente</th><th>Criticità</th><th>SLA</th><th>Stato</th></tr></thead><tbody>${D.nc.concat(D.nc).map(n=>`<tr data-nc="${n.id}"><td data-label="ID"><b>${n.id}</b></td><td data-label="Causa">${n.cause}</td><td data-label="Ente">${n.entity}</td><td data-label="Criticità">${badge(n.severity,statusType(n.severity))}</td><td data-label="SLA"><b>${n.sla}</b></td><td data-label="Stato">${badge(n.status,statusType(n.status))}</td></tr>`).join('')}</tbody></table></div>`;
    if(t==='csat') content=`${stats([['CSAT','4,6 / 5'],['Survey','186'],['Trend','+12,2%'],['Aree critiche','3']])}<div class="content-grid"><article class="card panel"><h3>Andamento soddisfazione</h3>${satisfactionChart()}</article><aside class="card panel"><h3>Survey per Ente</h3>${activeEntities().map((e,i)=>`<div class="tree-row"><span>${icon('shield')}</span><span><b>${e.name}</b><small style="display:block">${18+i*6} survey</small></span><strong>${(4.3+i*.1).toFixed(1).replace('.',',')} / 5</strong></div>`).join('')}</aside></div>`;
    return `${pageHero('Qualità & Controlli','Controlli di processo e risultato, LQA, non conformità e customer satisfaction.','shield','<button class="btn" data-action="new-check">+ Nuovo controllo</button>')}<div class="page-shell">${tabs([['overview','Overview'],['process','Controlli di processo'],['result','Controlli di risultato'],['lqa','LQA'],['nc','Non conformità'],['csat','Customer Satisfaction']])}${content}</div>`;
  }

  function catalogSection(kind){
    const configs={
      products:{title:'Prodotti',data:D.products,cols:['Codice','Denominazione','Produttore','Categoria','Certificazioni','Dosaggio','Stato']},
      materials:{title:'Materiale economale',data:D.materials,cols:['Codice','Articolo','Categoria','Stock','Autonomia','Stato']},
      machines:{title:'Macchine',data:D.machines,cols:['Asset ID','Marca','Modello','Tipologia','Ore','Prossima manutenzione','Stato']},
      equipment:{title:'Attrezzature',data:D.equipment,cols:['ID','Nome','Categoria','Descrizione','Stato']},
      uniforms:{title:'Divise',data:D.uniforms,cols:['Codice','Articolo','Descrizione tecnica','Certificazione','Assegnate','Stato']}
    }; const c=configs[kind]; const isCard=state.view==='card';
    const row=x=>{if(kind==='products')return [x.id,x.name,x.maker,x.category,x.certifications,x.dose,badge(x.status,statusType(x.status))];if(kind==='materials')return [x.id,x.name,x.category,`${x.stock}%`,`${Math.round(x.stock/x.avg)} giorni`,badge(x.status,statusType(x.status))];if(kind==='machines')return [x.id,x.brand,x.name,x.category,fmt.format(x.hours),x.next,badge(x.status,statusType(x.status))];if(kind==='equipment')return [x.id,x.name,x.category,x.description,badge(x.status,statusType(x.status))];return [x.id,x.name,x.description,x.certification,x.assigned,badge(x.status,statusType(x.status))]};
    return `${stats([[`${c.title} reali`,c.data.length,'Dato estratto dai PDF'],['Record attivi',c.data.length],['Documenti collegati',Math.max(12,c.data.length*2)],['Alert',kind==='materials'?2:1]])}${toolbar(`Cerca in ${c.title.toLowerCase()}`,`<button class="ghost-btn" data-toggle-view="${isCard?'table':'card'}">${icon('grid')} Vista ${isCard?'tabella':'card'}</button>`)}${isCard?`<div class="catalog-grid">${c.data.map((x,i)=>`<article class="card catalog-card" data-catalog="${kind}:${x.id}" tabindex="0"><span class="catalog-icon">${icon(catalogIcons[kind])}</span><h3>${x.name}</h3><p>${x.description||x.specs||x.category}</p><div class="tags"><span class="tag">${x.category||x.brand||x.certification}</span>${x.certifications?`<span class="tag">${x.certifications}</span>`:''}</div><footer><small>${x.id}</small>${badge(x.status||'Disponibile',statusType(x.status||''))}</footer></article>`).join('')}</div>`:`<div class="table-wrap"><table class="data-table"><thead><tr>${c.cols.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${c.data.map(x=>`<tr data-catalog="${kind}:${x.id}">${row(x).map((v,i)=>`<td data-label="${c.cols[i]}">${i===1?`<b>${v}</b>`:v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}`;
  }

  function cam(){
    const t=state.tab; let content='';
    if(t==='overview') content=`${stats([['Prodotti conformi CAM','15 / 15','Catalogo reale'],['Prodotti Ecolabel','10','Etichette da PDF'],['Macchine','19','Specifiche reali'],['Attrezzature sostenibili','32','Catalogo reale']])}<div class="content-grid"><article class="card panel"><div class="card-title"><div><h3>Consumo detergente / m²</h3><p>Lineage: KPI → Lotto → Ente → Presidio → Attività → Prodotto → Documento</p></div>${badge('Tracciato')}</div><div class="bar-chart">${['Apr','Mag','Giu','Lug','Ago','Set'].map((m,i)=>`<div class="bar-group"><i style="height:${42+i*6}%"></i><i style="height:${39+i*5}%"></i><span>${m}</span></div>`).join('')}</div></article><aside class="card panel"><h3>CAM Data Lineage</h3>${['Lotto 4','ASL 8 Cagliari','Rete presidi','Pulizia ordinaria','Ultra Blue','2,1 g/m²','Scheda tecnica / SDS'].map((x,i)=>`<button class="tree-row" data-action="lineage" style="width:100%;text-align:left"><span>${i+1}</span><b>${x}</b><span>→</span></button>`).join('')}</aside></div><div class="section-heading"><div><h2>Cataloghi reali integrati</h2><p>Un’unica master data source per CAM, consumi, manutenzioni e report.</p></div></div><div class="functional-grid">${[['Prodotti',D.products.length,'products'],['Materiale economale',D.materials.length,'materials'],['Macchine',D.machines.length,'machines'],['Attrezzature',D.equipment.length,'equipment']].map((x,i)=>`<article class="card functional-card" data-cam-tab="${x[2]}"><span class="card-icon">${icon(catalogIcons[x[2]])}</span><h3>${x[0]}</h3><p>${x[1]} record reali normalizzati dagli allegati tecnici.</p>${spark(i)}<button class="link-btn" data-cam-tab="${x[2]}">Apri catalogo →</button></article>`).join('')}</div>`;
    if(['products','materials','machines','equipment'].includes(t)) content=catalogSection(t);
    if(t==='consumption') content=`${stats([['Detergente / m²','3,2 g'],['Materiale / 1.000 m²','18,4 u.'],['Ore macchina','2.840'],['Consumo acqua','n.d.','Non calcolato senza fonte']])}<div class="overview-grid"><article class="card chart-card" style="grid-column:1/3"><h3>Consumi mensili per categoria</h3><div class="bar-chart">${['Apr','Mag','Giu','Lug','Ago','Set'].map((m,i)=>`<button class="bar-group" data-action="consumption" style="border:0;background:none"><i style="height:${40+i*8}%"></i><i style="height:${35+i*7}%"></i><span>${m}</span></button>`).join('')}</div></article><article class="card chart-card"><h3>Mix per categoria</h3><div class="donut" style="margin:auto"><span>100%<br><small>tracciato</small></span></div></article></div>`;
    if(t==='maintenance') content=`${stats([['Asset monitorati','19'],['Interventi pianificati','8'],['In scadenza','3'],['Efficienza media','97,4%']])}${toolbar('Cerca asset o manutenzione','<button class="btn" data-action="new-maintenance">+ Pianifica manutenzione</button>')}<div class="table-wrap"><table class="data-table"><thead><tr><th>Asset</th><th>Tipologia</th><th>Ore macchina</th><th>Ultima manutenzione</th><th>Prossima</th><th>Stato</th></tr></thead><tbody>${D.machines.map((m,i)=>`<tr data-catalog="machines:${m.id}"><td data-label="Asset"><b>${m.brand} ${m.name}</b></td><td data-label="Tipologia">${m.category}</td><td data-label="Ore">${fmt.format(m.hours)}</td><td data-label="Ultima">${12+i%12} lug 2026</td><td data-label="Prossima">${m.next}</td><td data-label="Stato">${badge(m.status,statusType(m.status))}</td></tr>`).join('')}</tbody></table></div>`;
    if(t==='documents') content=`${toolbar('Cerca scheda, SDS, Ecolabel o manuale')}<div class="document-grid">${['Schede tecniche prodotti','Schede dati di sicurezza','Certificazioni CAM','Ecolabel / Umweltzeichen','EPD / CFP / PSV','Registrazioni PMC','Manuali macchine','Registri manutenzione','Documenti materiali','Documenti divise','Protocolli disinfettanti','Report conformità mensile'].map((x,i)=>`<button class="card doc-card" data-action="document"><span>${icon('doc')}</span><span><b>${x}</b><small>${i<6?D.products.length:D.machines.length} documenti indicizzati</small></span><span>→</span></button>`).join('')}</div>`;
    return `${pageHero('CAM Control Center','Performance ambientale, conformità, tracciabilità, cataloghi e asset management.','leaf','<button class="btn" data-action="cam-report">Genera report CAM</button>')}<div class="page-shell">${tabs([['overview','Overview'],['products','Prodotti'],['materials','Materiale economale'],['machines','Macchine'],['equipment','Attrezzature'],['consumption','Consumi'],['maintenance','Manutenzioni'],['documents','Documentazione']])}${content}</div>`;
  }

  function reports(){
    const t=state.tab; const names={service:'Andamento servizio',nc:'Non conformità',camreport:'CAM',people:'Personale',consumptionreport:'Consumi',export:'Export'}; let content='';
    if(t==='overview'||t==='service') content=`${stats([['Report disponibili','48'],['Viste direzionali','7'],['Aggiornamento','Real time'],['Export generati','126']])}<div class="report-grid">${[['Andamento servizio','Prestazioni, frequenze, mq, addetti e valore residuo','chart'],['Non conformità','NC per Lotto, Ente, causa, criticità, stato e SLA','alert'],['CAM','Prodotti, quantità, Ecolabel, PMC, macchine e consumi','leaf'],['Personale','Addetti, monte ore, contratti, mansioni e formazione','users'],['Consumi','Prodotti, materiale economale e ore macchina','spray'],['Export personalizzato','Configura sezioni e formato di output','download']].map((r,i)=>`<article class="card report-card"><span class="catalog-icon">${icon(r[2])}</span><h3>${r[0]}</h3><p>${r[1]}</p>${spark(i)}<button class="link-btn" data-report="${['service','nc','camreport','people','consumptionreport','export'][i]}">Apri report →</button></article>`).join('')}</div>`;
    else if(t==='export') content=`<div class="content-grid"><article class="card panel"><h3>Genera report</h3><form class="login-form" id="reportForm"><label>Lotto<select name="lot"><option>Tutti i lotti</option>${D.lots.map(l=>`<option>${l.name}</option>`).join('')}</select></label><label>Ente<select name="entity"><option>Tutti gli enti</option>${D.lots.flatMap(l=>l.entities).map(e=>`<option>${e.name}</option>`).join('')}</select></label><label>Periodo<select name="period"><option>Ultimi 30 giorni</option><option>Ultimi 3 mesi</option><option>Anno corrente</option></select></label><label>Formato<select name="format"><option>PDF</option><option>XLSX</option><option>CSV</option></select></label><fieldset class="report-sections"><legend>Sezioni</legend>${['Andamento servizio','Non conformità','CAM','Personale','Consumi'].map(x=>`<label class="report-section-option"><input type="checkbox" name="sections" value="${x}" checked><span>${x}</span></label>`).join('')}</fieldset><button class="btn" type="submit">${icon('download')} Genera report</button></form></article><aside class="card panel"><h3>Ultimi export</h3>${['Report direzionale — Settembre','CAM Compliance — Q3','NC e SLA — Agosto','Personale — Consuntivo'].map((x,i)=>`<div class="tree-row"><span>${icon('doc')}</span><span><b>${x}</b><small style="display:block">PDF · ${2+i} MB</small></span><button class="link-btn" data-action="download">Scarica</button></div>`).join('')}</aside></div>`;
    else content=`${stats([[names[t],'Vista direzionale'],['Periodo','Ultimi 30 giorni'],['Record','1.248'],['Aggiornamento',D.meta.updated]])}${toolbar(`Cerca nel report ${names[t]}`,'<button class="btn" data-action="download">Scarica PDF</button>')}<div class="content-grid"><article class="card chart-card"><h3>${names[t]} · trend</h3><div class="bar-chart">${['Apr','Mag','Giu','Lug','Ago','Set'].map((m,i)=>`<div class="bar-group"><i style="height:${42+i*7}%"></i><i style="height:${39+i*6}%"></i><span>${m}</span></div>`).join('')}</div></article><aside class="card panel"><h3>Indicatori inclusi</h3>${['Classificazione area','Ambienti e mq','Prestazioni e frequenze','Numero addetti','Monte ore','Prodotti e quantità','Valore residuo'].map((x,i)=>`<div class="tree-row"><span>${i+1}</span><b>${x}</b>${badge('Incluso')}</div>`).join('')}</aside></div>`;
    return `${pageHero('Report & Analytics','Viste direzionali, reporting contrattuale ed esportazioni in formati elaborabili.','chart','<button class="btn" data-report="export">Genera report</button>')}<div class="page-shell">${tabs([['service','Andamento servizio'],['nc','Non conformità'],['camreport','CAM'],['people','Personale'],['consumptionreport','Consumi'],['export','Export']])}${content}</div>`;
  }

  const renderers={home,governance,planning,staff,interventions,quality,cam,reports};
  const defaults={home:'overview',governance:'overview',planning:'today',staff:'registry',interventions:'list',quality:'overview',cam:'overview',reports:'service'};
  const validTabs={governance:['overview','entities','structures','areas','roles','documents','audit'],planning:['today','calendar','pog','reclamation','periodic'],staff:['registry','shifts','attendance','activities','training','uniforms'],interventions:['list','kanban','timeline'],quality:['overview','process','result','lqa','nc','csat'],cam:['overview','products','materials','machines','equipment','consumption','maintenance','documents'],reports:['service','nc','camreport','people','consumptionreport','export']};
  let currentRoute='';

  function render(){
    const r=route();
    if(r!==currentRoute){state.tab=defaults[r];state.view='table';currentRoute=r;window.scrollTo({top:0,behavior:'smooth'});}
    app.innerHTML=renderers[r]();
    document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===r));
    document.querySelector('#mainNav').classList.remove('open'); document.querySelector('#menuToggle').setAttribute('aria-expanded','false');
    bindDynamic();
    if(r==='home') startSlider(); else stopSlider();
  }

  function bindDynamic(){
    const lot=document.querySelector('#lotFilter'), entity=document.querySelector('#entityFilter');
    if(lot) lot.addEventListener('change',()=>{state.lot=lot.value;state.entity='all';render();});
    if(entity) entity.addEventListener('change',()=>{state.entity=entity.value;});
    document.querySelector('#applyFilters')?.addEventListener('click',()=>{state.entity=document.querySelector('#entityFilter')?.value||'all';state.structure=document.querySelector('#structureFilter')?.value||'all';state.period=document.querySelector('#periodFilter')?.value||'30';render();toast(`Vista aggiornata: ${lotName()} · ${selectedEntity()}.`)});
    document.querySelector('#resetFilters')?.addEventListener('click',()=>{state.lot='all';state.entity='all';state.structure='all';state.period='30';render();toast('Filtri ripristinati.')});
    document.querySelectorAll('[data-local-search]').forEach(input=>input.addEventListener('input',()=>{
      const q=input.value.toLowerCase(); const container=input.closest('.page-shell')||document;
      container.querySelectorAll('tbody tr,.catalog-card,.doc-card,.ticket-card').forEach(el=>el.hidden=!el.textContent.toLowerCase().includes(q));
    }));
    document.querySelector('#reportForm')?.addEventListener('submit',e=>{e.preventDefault();toast('Report generato: la preview PDF è pronta.');});
  }

  function restartSlider(){
    stopSlider();
    if(document.hidden || route()!=='home' || !document.querySelector('#hero')) return;
    const progress=document.querySelector('.slide-progress');
    if(progress){progress.classList.remove('play');void progress.offsetWidth;progress.classList.add('play')}
    state.slider=setInterval(()=>changeSlide(1),6000);
  }
  function startSlider(){
    state.slide=0;
    restartSlider();
    const hero=document.querySelector('#hero');
    let x=0;
    hero?.addEventListener('touchstart',e=>x=e.changedTouches[0].clientX,{passive:true});
    hero?.addEventListener('touchend',e=>{const d=e.changedTouches[0].clientX-x;if(Math.abs(d)>45)changeSlide(d<0?1:-1)},{passive:true});
  }
  function stopSlider(){
    if(state.slider!==null){clearInterval(state.slider);state.slider=null}
    document.querySelector('.slide-progress')?.classList.remove('play');
  }
  document.addEventListener('visibilitychange',()=>document.hidden?stopSlider():restartSlider());
  window.addEventListener('pageshow',restartSlider);
  function changeSlide(dir,to=null){
    const slides=[...document.querySelectorAll('.slide')]; if(!slides.length)return;
    state.slide=to!==null?to:(state.slide+dir+slides.length)%slides.length;
    slides.forEach((s,i)=>s.classList.toggle('active',i===state.slide));document.querySelectorAll('.dot').forEach((d,i)=>d.classList.toggle('active',i===state.slide));
    restartSlider();
  }

  function openDrawer(title,eyebrow,body){
    document.querySelector('#drawerTitle').textContent=title;document.querySelector('#drawerEyebrow').textContent=eyebrow;document.querySelector('#drawerBody').innerHTML=body;
    document.querySelector('#overlay').hidden=false;const d=document.querySelector('#drawer');d.classList.add('open');d.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>d.querySelector('[data-close]').focus(),80);
  }
  function openModal(title,eyebrow,body){document.querySelector('#modalTitle').textContent=title;document.querySelector('#modalEyebrow').textContent=eyebrow;document.querySelector('#modalBody').innerHTML=body;document.querySelector('#modalWrap').hidden=false;document.body.style.overflow='hidden';setTimeout(()=>document.querySelector('#modalWrap [data-close]').focus(),80)}
  function closePanels(){document.querySelector('#overlay').hidden=true;document.querySelector('#drawer').classList.remove('open');document.querySelector('#drawer').setAttribute('aria-hidden','true');document.querySelector('#modalWrap').hidden=true;document.body.style.overflow=''}
  function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.querySelector('#toasts').append(el);setTimeout(()=>el.remove(),3500)}

  function entityDetail(id){const e=D.lots.flatMap(l=>l.entities.map(x=>({...x,lot:l.name}))).find(x=>x.id===id);if(!e)return;openDrawer(e.name,e.lot,`<div class="detail-kpis"><div><small>Superficie</small><strong>${fmt.format(e.surface)} m²</strong></div><div><small>Attività</small><strong>${scaled(184)}</strong></div><div><small>Conformità</small><strong>98,1%</strong></div></div>${e.note?`<p class="badge warning" style="white-space:normal">${e.note}</p>`:''}<h3>Classificazione per complessità</h3><div class="spec-list">${riskClasses.map((r,i)=>`<div><dt>${riskBadge(i)}</dt><dd>${fmt.format(e.risk[i])} m²</dd></div>`).join('')}</div><h3>Azioni</h3><div class="section-actions"><button class="btn" data-action="entity-open">Apri anagrafica</button><button class="ghost-btn" data-action="export">Esporta scheda</button></div>`)}
  function catalogDetail(kind,id){const map={products:D.products,materials:D.materials,machines:D.machines,equipment:D.equipment,uniforms:D.uniforms};const x=map[kind]?.find(v=>v.id===id);if(!x)return;let specs=[];if(kind==='products')specs=[['Produttore',x.maker],['Categoria',x.category],['Tipologia',x.type],['Applicazione',x.application],['Certificazioni',x.certifications],['Ecolabel',x.ecolabel||'Non riportato'],['PMC',x.pmc||'Non applicabile'],['Plastica riciclata',x.recycled||'Non riportato'],['Profumazione',x.fragrance],['Dosaggio',x.dose]];if(kind==='materials')specs=[['Categoria',x.category],['Descrizione',x.description],['Stock demo',x.stock+'%'],['Consumo medio demo',x.avg+' u./giorno'],['Stato',x.status]];if(kind==='machines')specs=[['Marca',x.brand],['Modello',x.name],['Tipologia',x.category],['Specifiche reali',x.specs],['Ore macchina demo',fmt.format(x.hours)],['Prossima manutenzione',x.next],['Stato',x.status]];if(kind==='equipment')specs=[['Categoria',x.category],['Descrizione reale',x.description],['Stato demo',x.status]];if(kind==='uniforms')specs=[['Codice articolo',x.id],['Descrizione tecnica',x.description],['Certificazione',x.certification],['Dotazioni assegnate demo',x.assigned],['Stato',x.status]];openDrawer(x.name||x.brand,kind==='products'?'Product master data':kind==='machines'?'Machine master data':'Catalogo reale',`<div class="detail-kpis"><div><small>ID univoco</small><strong>${x.id}</strong></div><div><small>Fonte</small><strong>PDF allegato</strong></div><div><small>CAM</small><strong>${kind==='products'||kind==='machines'?'Conforme':'Tracciato'}</strong></div></div>${x.description?`<p>${x.description}</p>`:''}<div class="subnav"><button class="active">Overview</button><button>Documenti</button><button>Consumi</button><button>Distribuzione</button></div><dl class="spec-list">${specs.map(s=>`<div><dt>${s[0]}</dt><dd>${s[1]}</dd></div>`).join('')}</dl><div class="section-actions" style="margin-top:18px"><button class="btn" data-action="document">Apri documentazione</button><button class="ghost-btn" data-action="export">Esporta scheda</button></div>`)}
  function ticketDetail(id){const x=D.tickets.find(v=>v.id===id)||D.tickets[0];openDrawer(x.id,'Service Desk',`<h3>${x.title}</h3><div class="detail-kpis"><div><small>Priorità</small><strong>${x.priority}</strong></div><div><small>SLA residuo</small><strong>${x.sla}</strong></div><div><small>Stato</small><strong>${x.status}</strong></div></div><dl class="spec-list">${[['Canale','Sistema informativo'],['Ente',x.entity],['Tipo',x.type],['Richiedente','Referente Demo'],['Area','Area operativa associata'],['Valore demo','€ 1.280'],['Prodotti','Ultra Blue'],['Evidenze','3 allegati']].map(s=>`<div><dt>${s[0]}</dt><dd>${s[1]}</dd></div>`).join('')}</dl><h3>Workflow</h3><div class="hierarchy">${['Richiesta','Presa in carico','Autorizzazione','Pianificazione','Esecuzione','Verifica','Chiusura'].map((s,i)=>`<div class="tree-row"><span>${i<4?'✓':'○'}</span><b>${s}</b>${i<4?badge('Completato'):badge('In attesa','warning')}</div>`).join('')}</div>`)}
  function ncDetail(id){const x=D.nc.find(v=>v.id===id)||D.nc[0];openDrawer(x.id,'Non conformità',`<div class="detail-kpis"><div><small>Criticità</small><strong>${x.severity}</strong></div><div><small>SLA</small><strong>${x.sla}</strong></div><div><small>Stato</small><strong>${x.status}</strong></div></div><dl class="spec-list">${[['Origine','Controllo di risultato'],['Ente',x.entity],['Causa',x.cause],['Responsabile','Qualità Demo'],['Azione correttiva','Ripetizione gratuita della prestazione'],['Evidenze','Before / After'],['Tempo massimo','4 h continuative · 48 h periodiche']].map(s=>`<div><dt>${s[0]}</dt><dd>${s[1]}</dd></div>`).join('')}</dl><button class="btn" data-action="close-nc" style="margin-top:18px">Registra verifica</button>`)}
  function personDetail(id){const p=D.people.find(v=>v.id===id);openDrawer(p.name,'Scheda operatore',`<div class="detail-kpis"><div><small>Matricola</small><strong>${p.id}</strong></div><div><small>Monte ore</small><strong>${p.hours} h</strong></div><div><small>Stato</small><strong>${p.status}</strong></div></div><dl class="spec-list">${[['Mansione',p.role],['Lotto',`Lotto ${p.lot}`],['Ente',p.entity],['Turno',p.shift],['Formazione','Valida'],['Presenza','Registrata in tempo reale']].map(s=>`<div><dt>${s[0]}</dt><dd>${s[1]}</dd></div>`).join('')}</dl><h3>Dotazioni assegnate</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Codice</th><th>Descrizione</th><th>Taglia</th><th>Consegna</th><th>Stato</th></tr></thead><tbody>${D.uniforms.slice(0,4).map((u,i)=>`<tr data-catalog="uniforms:${u.id}"><td>${u.id}</td><td><b>${u.name}</b></td><td>${['M','M','48','L'][i]}</td><td>12 feb 2026</td><td>${badge(i===3?'In riordino':'Consegnato',i===3?'warning':'')}</td></tr>`).join('')}</tbody></table></div>`)}

  function searchModal(){openModal('Ricerca globale','CMD / CTRL + K',`<label class="search-field">${icon('search')}<input id="globalSearch" autofocus placeholder="Cerca enti, operatori, ticket, prodotti, asset…"></label><div class="search-results" id="searchResults"><p style="color:var(--muted)">Digita almeno 2 caratteri. Prova “Tea”, “FIMAP GXL”, “ECO Z” o “AO Brotzu”.</p></div>`);const input=document.querySelector('#globalSearch'),out=document.querySelector('#searchResults');input.focus();input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();if(q.length<2){out.innerHTML='<p style="color:var(--muted)">Digita almeno 2 caratteri.</p>';return}const all=[...D.lots.flatMap(l=>l.entities.map(x=>({type:'Ente',name:x.name,id:x.id,action:'entity'}))),...D.products.map(x=>({type:'Prodotto',name:x.name,id:x.id,action:'products'})),...D.materials.map(x=>({type:'Materiale',name:x.name,id:x.id,action:'materials'})),...D.machines.map(x=>({type:'Macchina',name:`${x.brand} ${x.name}`,id:x.id,action:'machines'})),...D.equipment.map(x=>({type:'Attrezzatura',name:x.name,id:x.id,action:'equipment'})),...D.uniforms.map(x=>({type:'Divisa',name:`${x.id} · ${x.name}`,id:x.id,action:'uniforms'})),...D.tickets.map(x=>({type:'Ticket',name:`${x.id} · ${x.title}`,id:x.id,action:'ticket'})),...D.nc.map(x=>({type:'NC',name:`${x.id} · ${x.cause}`,id:x.id,action:'nc'})),...D.people.map(x=>({type:'Operatore demo',name:x.name,id:x.id,action:'person'}))].filter(x=>x.name.toLowerCase().includes(q)).slice(0,12);out.innerHTML=all.length?all.map(x=>`<button class="search-result" data-search-action="${x.action}:${x.id}"><i>${x.type[0]}</i><span><b>${x.name}</b><small>${x.type} · ${x.id}</small></span><span>→</span></button>`).join(''):'<p>Nessun risultato.</p>'})}
  function loginModal(){openModal('Area riservata','Accesso dimostrativo',`<form class="login-form" id="loginForm"><label>Nome utente<input name="username" value="mario.rossi.demo" required></label><label>Password<input type="password" name="password" value="demo2026" required></label><label>Ruolo<select name="role">${['DEC','RUP','Responsabile Lotto','Referente Ente','Qualità','Admin'].map(x=>`<option>${x}</option>`).join('')}</select></label><button class="btn" type="submit">Accedi alla piattaforma</button><small style="color:var(--muted)">Accesso simulato: nessuna credenziale viene trasmessa.</small></form>`);document.querySelector('#loginForm').addEventListener('submit',e=>{e.preventDefault();state.role=new FormData(e.target).get('role');closePanels();toast(`Accesso demo effettuato come ${state.role}.`)})}
  function reportModal(){openModal('Genera report','Configurazione export',`<form class="login-form" id="quickReport"><label>Lotto<select><option>Tutti i lotti</option>${D.lots.map(l=>`<option>${l.name}</option>`).join('')}</select></label><label>Ente<select><option>Tutti gli enti</option>${D.lots.flatMap(l=>l.entities).map(e=>`<option>${e.name}</option>`).join('')}</select></label><label>Periodo<select><option>Ultimi 30 giorni</option><option>Ultimi 3 mesi</option><option>Anno corrente</option></select></label><label>Formato<select><option>PDF</option><option>XLSX</option><option>CSV</option></select></label><button class="btn" type="submit">Genera report</button></form>`);document.querySelector('#quickReport').addEventListener('submit',e=>{e.preventDefault();closePanels();toast('Report generato e disponibile nella sezione Export.')})}

  document.addEventListener('click',e=>{
    if(e.target.closest('[data-classification]')){openDrawer('Codici colore complessità aree sanitarie','Classificazione',`<div class="classification-list">${riskClasses.map((r,i)=>`<button class="ghost-btn" data-risk="${i}">${riskBadge(i)} →</button>`).join('')}</div>`);return;}
    const close=e.target.closest('[data-close]');if(close){closePanels();return}
    if(e.target.id==='overlay'){closePanels();return}
    const nav=e.target.closest('[data-nav]');if(nav){location.hash=`#/${nav.dataset.nav}`;return}
    const tab=e.target.closest('[data-tab]');if(tab){state.tab=tab.dataset.tab;render();return}
    const camTab=e.target.closest('[data-cam-tab]');if(camTab){state.tab=camTab.dataset.camTab;render();return}
    const report=e.target.closest('[data-report]');if(report){state.tab=report.dataset.report;location.hash='#/reports';if(route()==='reports')render();return}
    const slideDir=e.target.closest('[data-slide-dir]');if(slideDir){changeSlide(Number(slideDir.dataset.slideDir));return}
    const slideTo=e.target.closest('[data-slide-to]');if(slideTo){changeSlide(0,Number(slideTo.dataset.slideTo));return}
    const lot=e.target.closest('[data-lot-jump]');if(lot){state.lot=lot.dataset.lotJump;state.entity='all';render();toast(`Filtro applicato: Lotto ${state.lot}.`);return}
    const ent=e.target.closest('[data-entity-detail]');if(ent){entityDetail(ent.dataset.entityDetail);return}
    const catalog=e.target.closest('[data-catalog]');if(catalog){const [kind,id]=catalog.dataset.catalog.split(':');catalogDetail(kind,id);return}
    const prod=e.target.closest('[data-product]');if(prod){catalogDetail('products',prod.dataset.product);return}
    const ticket=e.target.closest('[data-ticket]');if(ticket){ticketDetail(ticket.dataset.ticket);return}
    const nc=e.target.closest('[data-nc]');if(nc){ncDetail(nc.dataset.nc);return}
    const person=e.target.closest('[data-person]');if(person){personDetail(person.dataset.person);return}
    const search=e.target.closest('[data-search-action]');if(search){const [kind,id]=search.dataset.searchAction.split(':');closePanels();if(kind==='entity')entityDetail(id);else if(kind==='ticket')ticketDetail(id);else if(kind==='nc')ncDetail(id);else if(kind==='person')personDetail(id);else catalogDetail(kind,id);return}
    const risk=e.target.closest('[data-risk]');if(risk){const labels=riskClasses.map(r=>r.label+' ('+r.code+')');openDrawer(labels[+risk.dataset.risk],'Classificazione per complessità',`<p>Drill-down delle superfici per Lotto ed Ente.</p><div class="hierarchy">${activeEntities().map(x=>`<div class="tree-row"><span>${riskBadge(+risk.dataset.risk)}</span><b>${x.name}</b><strong>${fmt.format(x.risk[+risk.dataset.risk])} m²</strong></div>`).join('')}</div>`);return}
    const kpi=e.target.closest('[data-kpi]');if(kpi){const x=kpis()[+kpi.dataset.kpi];openDrawer(x[1],'KPI · Drill-down',`<div class="detail-kpis"><div><small>Valore</small><strong>${x[2]}</strong></div><div><small>Trend</small><strong>${x[3]}</strong></div><div><small>Filtro</small><strong>${lotName()}</strong></div></div><p>Il valore è aggiornato dal dataset centrale e rispetta i filtri Lotto → Ente → Presidio → Periodo.</p><button class="btn" data-action="kpi-report">Genera report correlato</button>`);return}
    const toggle=e.target.closest('[data-toggle-view]');if(toggle){state.view=toggle.dataset.toggleView;render();return}
    const action=e.target.closest('[data-action]');if(action){const a=action.dataset.action;if(a==='new-ticket'){openModal('Nuova richiesta','Service Desk',`<form class="login-form" id="ticketForm"><label>Tipologia<select><option>Extra-canone</option><option>A chiamata</option><option>Straordinario</option><option>Anomalia</option><option>Reclamo</option><option>Informazione</option></select></label><label>Ente<select>${activeEntities().map(x=>`<option>${x.name}</option>`).join('')}</select></label><label>Motivo<textarea rows="4" required></textarea></label><label>Priorità<select><option>Media</option><option>Alta</option><option>Critica</option></select></label><button class="btn" type="submit">Registra richiesta</button></form>`);document.querySelector('#ticketForm').addEventListener('submit',ev=>{ev.preventDefault();closePanels();toast('Richiesta TCK-DEMO registrata e presa in carico.')});return}if(a==='cam-report'){reportModal();return}toast({export:'Esportazione preparata.',download:'Download demo avviato.',document:'Preview documento aperta.',personalize:'Vista personale salvata.',notification:'Notifica contrassegnata come letta.','save-permissions':'Autorizzazioni aggiornate.','complete-check':'Controllo completato e verbale registrato.','validate-pog':'POG validati con successo.','close-nc':'Verifica registrata: NC aggiornata.'}[a]||'Operazione completata nella demo.');return}
  });

  document.querySelector('#menuToggle').addEventListener('click',e=>{const n=document.querySelector('#mainNav');n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',n.classList.contains('open'))});
  document.querySelector('#searchBtn').addEventListener('click',searchModal);document.querySelector('#notifyBtn').addEventListener('click',()=>openDrawer('Notifiche','Notification center',notificationItems(true)));document.querySelector('#loginBtn').addEventListener('click',loginModal);document.querySelector('#profileBtn').addEventListener('click',()=>openDrawer('Mario Rossi','Profilo utente',`<div class="detail-kpis"><div><small>Ruolo attivo</small><strong>${state.role}</strong></div><div><small>Ambito</small><strong>Tutti i lotti</strong></div><div><small>Ultimo accesso</small><strong>Oggi, 12:04</strong></div></div><button class="btn" data-action="profile">Gestisci profilo</button>`));
  document.querySelectorAll('[data-legal]').forEach(b=>b.addEventListener('click',()=>openModal(b.textContent,'Informazioni',`<p>Contenuto dimostrativo della piattaforma RAS SERVICE HUB.</p><p>Versione 2.1.0 · Ambiente di presentazione tecnica.</p>`)));
  document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();searchModal()}if(e.key==='Escape')closePanels()});
  window.addEventListener('scroll',()=>document.querySelector('#appHeader').classList.toggle('scrolled',scrollY>8),{passive:true});
  window.addEventListener('hashchange',render);
  render();
})();
