/* Milanosport: cluster operativi dal prospetto del cliente; dati attività dimostrativi. */
const clusters=[{id:1,name:'Ovest / Parri',sites:[18,0,4,19,16],hours:[7802,6234,6642,3864,1639]},{id:2,name:'Centro-Ovest',sites:[26,22,25,24,7,5],hours:[2336,8775,3462,5773,1661,5635]},{id:3,name:'Murat / Nord',sites:[17,23,14,13,10],hours:[7545,8459,6727,4120,5300]},{id:4,name:'Bacone / Centro-Est',sites:[1,2,20,12,8,9],hours:[8696,5759,2613,8689,3280,525]},{id:5,name:'Sud',sites:[21,15,6,3,11],hours:[7327,6780,4434,1696,1490]}];
Object.assign(state,{cluster:0,period:'all',activity:'all'});
clusters.forEach(c=>c.sites.forEach((id,i)=>Object.assign(facilities[id],{cluster:c.id,annualHours:c.hours[i],hub:i===0})));
window.facilityMatches=f=>(!state.cluster||f.cluster===state.cluster)&&(state.facility<0||f.id===state.facility);
const demoToday='2026-09-16';
activities.forEach(a=>a.date='16/09/2026');ncs.forEach(n=>n.date='16/09/2026');
function dateInPeriod(value){if(state.period==='all'||!value)return true;const parts=value.split('/');const iso=parts.length===3?`${parts[2]}-${parts[1]}-${parts[0]}`:value;const d=Date.parse(iso),today=Date.parse(demoToday);if(!Number.isFinite(d))return true;return state.period==='today'?d===today:state.period==='week'?d>=today-6*86400000&&d<=today:iso.startsWith('2026-09');}
window.matchScope=r=>facilityMatches(facilities[r.facility])&&dateInPeriod(r.date)&&(!r.kind||state.activity==='all'||r.kind===state.activity)&&(!String(r.id).startsWith('EXT-')||state.activity==='all'||state.activity==='extra');
function filterOptions(items,value){return items.map(([v,l])=>`<option value="${v}" ${String(v)===String(value)?'selected':''}>${esc(l)}</option>`).join('');}
filterbar=function(){if(state.view==='sustainability'&&window.sustainabilityFilterbar)return window.sustainabilityFilterbar();return `<div class="filterbar dashboard-filters">${icon('filter')}<label>Cluster<select id="cluster-select">${filterOptions([[0,'Tutti i cluster'],...clusters.map(c=>[c.id,c.id===2?`Cluster 2 – ${c.name}`:`Cluster ${c.id} · ${c.name}`])],state.cluster)}</select></label><label>Impianto<select id="facility-select">${filterOptions([[-1,'Tutti gli impianti'],...facilities.filter(f=>!state.cluster||f.cluster===state.cluster).map(f=>[f.id,f.name])],state.facility)}</select></label><label>Periodo<select id="period-select">${filterOptions([['all','Tutti i periodi'],['today','Oggi · 16 set (demo)'],['week','Ultimi 7 giorni'],['month','Settembre 2026']],state.period)}</select></label><label>Attività<select id="activity-select">${filterOptions([['all','Tutte le attività'],['ordinary','Servizio ordinario'],['complementary','Servizi complementari'],['extra','Straordinarie']],state.activity)}</select></label><button class="link" data-action="reset">${icon('refresh')}Reset filtri</button></div>`;};
metrics=function(){const a=scoped(activities).filter(x=>x.status!=='Da attivare'),cert=a.filter(x=>x.status==='Certificata').length,ts=scoped(tickets),people=scoped(personnel),hrs=a.filter(x=>x.status==='Certificata').length*37/60;return `<div class="metrics">${metric('Attività certificate',(a.length?100*cert/a.length:0).toFixed(1).replace('.',',')+'<small>%</small>',`${cert} / ${a.length} attività`,'shield','#149a79','#e5f7ef')}${metric('Operatori attivi',people.filter(p=>p.presence!=='Assente').length,'Copertura del servizio · demo','users','#1687d4','#eaf4ff')}${metric('Ore erogate',hrs.toFixed(1).replace('.',',')+` <small>/ ${(a.length*37/60).toFixed(1)} h</small>`,'Consuntivate / pianificate · demo','clock','#7861cd','#f0edfc')}${metric('Straordinarie',ts.filter(t=>t.status!=='Completata').length,`${ts.filter(t=>t.status==='In esecuzione').length} in esecuzione`,'ticket','#d4932a','#fff4e3')}${metric('NC & SLA',scoped(ncs).filter(n=>n.status!=='Risolta').length,'Non conformità aperte','alert','#dc6271','#fff0f2')}${metric('CAM & dotazioni','100<small>%</small>','Prodotti conformi · dati demo','leaf','#249d85','#eaf8f3')}</div>`;};
function setDashboardFilter(id,value){if(id==='cluster-select'){state.cluster=Number(value);if(state.facility>=0&&state.cluster&&facilities[state.facility].cluster!==state.cluster)state.facility=-1;}if(id==='facility-select'){state.facility=Number(value);if(state.facility>=0&&state.cluster&&facilities[state.facility].cluster!==state.cluster)state.cluster=facilities[state.facility].cluster;}if(id==='period-select')state.period=value;if(id==='activity-select')state.activity=value;state.page=ops.page=1;render();}
document.addEventListener('change',e=>{if(['cluster-select','facility-select','period-select','activity-select'].includes(e.target.id)){e.stopImmediatePropagation();setDashboardFilter(e.target.id,e.target.value);}},true);
const oldHeroMarkup=heroMarkup;let slideElapsed=0,slideLast=0,slideFrame=0,slidePaused=false;
heroMarkup=function(){return oldHeroMarkup().replaceAll('<span></span>','<span><i></i></span>').replace('</small></div>','</small><button class="slider-pause" data-slider-pause aria-label="'+(slidePaused?'Riprendi slider':'Pausa slider')+'">'+(slidePaused?'▶':'Ⅱ')+'</button></div>');};
function tickSlider(now){if(state.view!=='home'){slideFrame=0;return;}const delta=slideLast?now-slideLast:0;slideLast=now;if(!slidePaused&&!document.hidden&&!document.querySelector('dialog[open]'))slideElapsed+=Math.min(delta,100);if(slideElapsed>=6000){slideElapsed=0;ops.hero=(ops.hero+1)%heroSlides.length;document.querySelector('.home-hero').innerHTML=heroMarkup();}document.querySelectorAll('[data-hero]').forEach((b,i)=>b.style.setProperty('--slide-progress',i===ops.hero?slideElapsed/6000:i<ops.hero?1:0));slideFrame=requestAnimationFrame(tickSlider);}
const baseRender=render;render=function(){cancelAnimationFrame(slideFrame);slideFrame=0;slideLast=slideElapsed=0;baseRender();if(state.view==='home')slideFrame=requestAnimationFrame(tickSlider);};
function loginDEC(){const d=document.getElementById('form-dialog');d.innerHTML=`<div class="login-content"><button class="icon-btn login-close" data-close-login aria-label="Chiudi">${icon('close')}</button><img class="login-mark" src="assets/logo.png" alt="Milanosport Hub"><h2>Benvenuto nell’Area DEC</h2><p>Il tuo punto di accesso al controllo del servizio.</p><form id="dec-login-form" class="login-form"><label>Nome utente<input name="username" autocomplete="off" required value="dec.demo"></label><label>Password<input name="password" type="password" autocomplete="off" required value="demo"></label><div class="login-demo-note">Accesso dimostrativo. Usa i dati già compilati: non vengono inviati né salvati. Non inserire credenziali reali.</div><button class="btn primary" type="submit">Accedi all’Area DEC ${icon('arrow')}</button></form></div>`;d.showModal();}
function pdiRows(){const total=Math.round(facilities.filter(facilityMatches).reduce((s,f)=>s+f.annualHours,0)/12),a=Math.round(total*.75),b=Math.round(total*.15);return [['Servizio ordinario',a,'97,8%','Validato'],['Servizi complementari',b,'93,1%','Validato'],['Attività straordinarie',total-a-b,'92,3%','In verifica'],['Compliance Management',scoped(ncs).length+' NC','84% chiuse','Monitorato']];}
function pdiScope(){return [state.cluster?'Cluster '+state.cluster:'Tutti i cluster',selected()?.name||'Tutti gli impianti'].join(' · ');}
pdiDetail=function(){let d=document.getElementById('pdi-modal');if(!d){d=document.createElement('dialog');d.id='pdi-modal';d.className='wide-modal';document.body.append(d);}const rows=pdiRows(),max=Math.max(...rows.slice(0,3).map(r=>r[1]),1);d.setAttribute('aria-labelledby','pdi-title');d.innerHTML=`<div class="pdi-content"><button class="icon-btn modal-close" data-close-pdi aria-label="Chiudi piano">${icon('close')}</button><div class="pdi-keyline"></div><h2 id="pdi-title">Piano Dettagliato degli Interventi</h2><p class="pdi-subtitle">Pianificazione operativa con ore programmate, avanzamento e stato documentale per il periodo corrente.</p><div class="pdi-scope"><span>Ambito monitorato</span><b>${esc(pdiScope())}</b></div><div class="pdi-grid"><section class="pdi-panel"><h3>PDI · settembre 2026</h3><div class="table-scroll"><table><thead><tr><th>Ambito</th><th>Ore</th><th>Avanzamento</th><th>Stato</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>`<td>${esc(v)}${i===1&&typeof v==='number'?' h':''}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section><section class="pdi-panel"><h3>Ripartizione mensile delle ore</h3><svg class="pdi-chart" viewBox="0 0 380 300" role="img" aria-label="Ore programmate per servizio: ${rows.slice(0,3).map(r=>r[0]+' '+r[1]).join(', ')}">${[0,.25,.5,.75,1].map(v=>`<line x1="40" x2="375" y1="${255-v*210}" y2="${255-v*210}" stroke="#e3eaf1" stroke-dasharray="4 4"/><text x="34" y="${259-v*210}" text-anchor="end">${Math.round(max*v)}</text>`).join('')}${rows.slice(0,3).map((r,i)=>`<rect x="${54+i*110}" y="${255-r[1]/max*210}" width="78" height="${r[1]/max*210}" rx="10" fill="#087cab"/><text x="${93+i*110}" y="${245-r[1]/max*210}" text-anchor="middle">${r[1]} h</text><text x="${93+i*110}" y="280" text-anchor="middle">${['Ordinario','Complementari','Straordinarie'][i]}</text>`).join('')}</svg></section></div><p class="pdi-note">Simulazione: ore annuali del prospetto cluster ripartite su 12 mesi e tra servizi a scopo illustrativo. Avanzamenti e stati sono esempi; il PDI approvato deve essere collegato.</p><div class="pdi-actions"><button class="btn" data-pdi-export="pdf">${icon('download')}Esporta PDF</button><button class="btn" data-pdi-export="xlsx">${icon('file')}Esporta XLSX</button></div></div>`;d.showModal();};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.action==='reset'){e.stopImmediatePropagation();Object.assign(state,{cluster:0,facility:-1,period:'all',activity:'all',search:'',status:'all',page:1});Object.assign(ops,{page:1,susCategory:'all',susType:'all',susStatus:'all',query:''});render();}if(b.hasAttribute('data-dec-login'))loginDEC();if(b.hasAttribute('data-close-login'))document.getElementById('form-dialog').close();if(b.hasAttribute('data-close-pdi'))document.getElementById('pdi-modal').close();if(b.dataset.pdiExport==='pdf')window.print();if(b.dataset.pdiExport==='xlsx')downloadBlob(makeXlsx([['PDI · settembre 2026 · DATI DIMOSTRATIVI'],[pdiScope()],['Ambito','Ore / NC','Avanzamento','Stato'],...pdiRows(),['Ripartizione mensile illustrativa, non PDI approvato']]),'Milanosport-PDI-demo.xlsx');if(b.dataset.hero!==undefined){slideElapsed=slideLast=0;}if(b.hasAttribute('data-slider-pause')){slidePaused=!slidePaused;b.textContent=slidePaused?'▶':'Ⅱ';b.setAttribute('aria-label',slidePaused?'Riprendi slider':'Pausa slider');}if(b.dataset.selectFacility!==undefined){const id=Number(b.dataset.selectFacility);if(state.cluster&&facilities[id])state.cluster=facilities[id].cluster;}},true);
document.addEventListener('submit',e=>{if(e.target.id==='dec-login-form'){e.preventDefault();e.stopImmediatePropagation();document.getElementById('form-dialog').close();e.target.reset();navigate('dashboard');}},true);
render();
